apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
data:
  DB_HOST: 'database-service'
  DB_TYPE: 'postgres'
  DB_PORT: '5432'
  DB_USER: 'postgres'
  DB_DB: 'database_postgres'
  BASE_URL: 'http://localhost:3000'
  NODE_ENV: 'production'
  NODE_OPTIONS: '--max-old-space-size=400'