apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  ports:
  - port: 5432
  selector:
    app: database
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  serviceName: 'database-service'
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database_postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapRef:
              name: url-shortener-config
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: url-shortener-secrets
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapRef:
              name: url-shortener-config
              key: DB_NAME
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ 'ReadWriteOnce' ]
      resources:
        requests:
          storage: 1